routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@update')->name('profile-update');

Route::group(['prefix' => 'university','as'=>'university.'], function () {
    Route::get('/', ['uses'=>'UniversityController@index','as'=>'index'])->middleware("can:university-list");
    Route::Post('/save', ['uses'=>'UniversityController@save','as'=>'save'])->middleware("can:university-list");
    Route::Post('/delete', ['uses'=>'UniversityController@delete','as'=>'delete'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'UniversityController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'faculty', 'as' => 'faculty.'],function(){
    Route::post('/delete',['uses' => 'FacultyController@delete','as' => 'delete'])->middleware("can:university-list");
    Route::post('/update',['uses' => 'FacultyController@update','as' => 'update'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'FacultyController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'offers','as'=>'offers.'], function () {
    Route::get('/', ['uses'=>'OfferController@index','as'=>'index'])->middleware("can:offer-list");
    Route::post('/save', ['uses'=>'OfferController@store','as'=>'save'])->middleware("can:offer-add");
    Route::get('/application/{offer_id}', ['uses'=>'OfferController@get_applications','as'=>'get_applications'])->middleware("can:offer-applications-list");
    Route::post('/edit', ['uses'=>'OfferController@edit','as'=>'edit'])->middleware("can:offer-edit");

    //Admin Routes
    Route::post('/delete', ['uses'=>'OfferController@delete','as'=>'delete'])->middleware("can:offer-delete");
    Route::get('/approve/{id}', ['uses'=>'OfferController@approve','as'=>'approve']);
    Route::get('/reject/{id}', ['uses'=>'OfferController@reject','as'=>'reject']);
//    Route::get('/edit/offer/{id}/{action}', ['uses'=>'OfferController@canEditOffer','as'=>'can-edit-offer']);
});

Route::group(['prefix' => 'files','as'=>'files.'], function () {
    Route::get('/', ['uses'=>'NoteController@index','as'=>'index']);

    Route::group(['prefix' => 'notes','as'=>'notes.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'NoteController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'NoteController@delete_file','as'=>'delete']);
        Route::post('/upload', ['uses'=>'NoteController@upload_files','as'=>'upload']);
        Route::get('list_ajax/{faculty_id}', 'NoteController@files_ajax');
    });

    Route::group(['prefix' => 'solutions','as'=>'solutions.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'SolutionController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'SolutionController@delete','as'=>'delete']);
        Route::post('/upload', ['uses'=>'SolutionController@upload','as'=>'upload']);
    });

});

Route::group(['prefix' => 'profile','as'=>'profile.'], function () {
    Route::get('/{id}', ['uses'=>'UserController@view_profile','as'=>'view']);
});


Route::group(['prefix' => 'user','as'=>'user.'], function () {
    Route::get('/list', ['uses'=>'UserController@index','as'=>'index']);
    Route::post('/register', ['uses'=>'UserController@register','as'=>'register']);
    Route::get('/admin', ['uses'=>'UserController@admin_index','as'=>'index.admin']);
    Route::get('/permission', ['uses'=>'UserController@getPermission','as'=>'permission']);
    Route::Post('/permission/add', ['uses'=>'UserController@savePermission','as'=>'permission.add']);
    Route::get('/assign_permission/{id}', ['uses'=>'UserController@assign_permission', 'as'=>'assign_permission']);
    Route::post('/assign_permission/store', ['uses'=>'UserController@assign_permission_store', 'as'=>'assign_permission_store']);
    Route::post('/permission_view', ['uses'=>'UserController@permission_view', 'as'=>'permission_view']);
});

Route::group(['prefix' => 'job','as'=>'job.'], function () {
    Route::get('/', ['uses'=>'JobController@index','as'=>'index']);
    Route::post('/save', ['uses'=>'JobController@store','as'=>'save']);
    Route::get('/application/{job_id}', ['uses'=>'JobController@get_applications','as'=>'get_applications']);
    Route::post('/update', ['uses'=>'JobController@update','as'=>'update']);
});


Route::get('/setup', ["uses"=>'SetupController@setup'])->name('setup');
Route::post('/setup/run', ["uses"=>'SetupController@setup_run'])->name('setup.run');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $dates = ['deadline'];

    public function job_provider()
    {
        return $this->belongsTo(User::class,'provider');
    }

    public function applications()
    {
        return $this->hasMany(JobApplication::class,'job_id');
    }
}

app/Http/Controllers/Api/JobController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helper\Tools;
use App\Job;
use App\JobApplication;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class JobController extends Controller
{
    public function jobListing()
    {
        $now = date('Y-m-d');
        $data = Job::where('deadline','>',$now)->with('job_provider')->get();
        $responseData = Tools::setResponse(false,'Job Listing Successfull',$data,'');

        return response()->json($responseData);
    }

    public function apply(Request $request)
    {
        $this->validate($request, [
            'job_id' => 'required',
            'app_user_id' => 'required'
        ]);

        $job = Job::find($request->job_id);
        if (is_null($job)){
            $responseData = Tools::setResponse(true,'job_not_found','','');
        }else{
            $check_application = JobApplication::where('app_user_id', $request->app_user_id)->where('job_id', $request->job_id)->get();
            if ($check_application->count() > 0){
                $responseData = Tools::setResponse(true,'already_applied','','');
            }else{
                $apply = new JobApplication();
                $apply->app_user_id = $request->app_user_id;
                $apply->job_id = $job->id;
                $apply->save();
                $responseData = Tools::setResponse(false,'job_applied_successfully','','');
            }
        }

        return response()->json($responseData);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Job;
use App\JobApplication;
use App\User;
use Illuminate\Http\Request;
use Auth;

class JobController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['jobs'] = Job::with(['job_provider','applications'])->get();
        $data['providers'] = User::where('user_type','user')->get();
        return view('job.index', $data);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'deadline' => 'required',
            'job_type' => 'required',
            'location' => 'required|max:200',
            'designation' => 'required|max:255',
        ]);
//        dd($request->all());
        $job = new Job();
        $job->title = $request->title;
        $job->deadline = $request->deadline;
        $job->job_type = $request->job_type;
        $job->location = $request->location;
        $job->designation = $request->designation;
        $job->description = $request->description;
        if (isset($request->provider)){
            $job->provider = $request->provider;
        }else{
            $job->provider = Auth::user()->id;
        }

        $job->save();
        return redirect()->back();
    }

    public function get_applications($job_id)
    {
        $data['offer'] = Job::find($job_id);
        $data['applications'] = JobApplication::where('job_id', $job_id)->with('app_user')->get();

        return view('job.applications', $data);
    }

    public function update(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'deadline' => 'required',
            'job_type' => 'required',
            'designation' => 'required|max:255',
            'location' => 'required|max:200'
        ]);


        $job = Job::findOrFail($request->job_id);
        $job->title = $request->title;
        $job->deadline = $request->deadline;
        $job->designation = $request->designation;
        $job->location = $request->location;
        $job->description = $request->description;
        
        if (isset($request->provider)){
            $job->provider = $request->provider;
        }else{
            $job->provider = Auth::user()->id;
        }

        $job->save();

        return redirect()->back();
    }
}

resources/views/job/add-job-modal.blade.php
<div class="modal fade bs-example-modal-lg" id="add-job" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel">Add Job / Intern</h4>
            </div>
            <form method="post" action="{{ route('job.save') }}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    {{--<div class="form-group">--}}
                        {{--<label for="input-file-now">Image</label>--}}
                        {{--<input type="file" name="image" id="input-file-now" class="dropify" />--}}
                    {{--</div>--}}
                    <div class="form-group">
                        <label for="input-file-now">Title</label>
                        <input type="text" name="title" value="{{old('title')}}" class="form-control" placeholder="Enter job title" />
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Deadline</label>
                        <div class="input-daterange input-group" id="date-range">
                            <input type="text" class="form-control datepicker-autoclose" name="deadline" value="{{old('deadline')}}" placeholder="Deadline" autocomplete="off" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input-file-now">Job Type</label>
                        <select name="job_type" id="" class="form-control">
                            <option value="Internship">Internship</option>
                            <option value="Job">Job</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="input-file-now">Job Location</label>
                        <input type="text" name="location" value="{{old('location')}}" class="form-control" placeholder="Enter job location" />
                        @error('location')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>

                    @if (Auth::check() AND Auth::user()->user_type=="admin")
                        <div class="form-group">
                            <label for="input-file-now">Provider</label>
                            <select name="provider" id="" class="form-control">
                                <option value="Internship">--select--</option>
                                @foreach($providers as $value)
                                    <option value="{{ $value->id }}">{{ $value->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="input-file-now">Designation</label>
                        <input type="text" name="designation" value="{{old('designation')}}" class="form-control" placeholder="Enter designation" />
                        @error('designation')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="input-file-now">Description <span class="text-warning">( optional )</span></label>
                        <textarea name="description" class="form-control textarea_editor" placeholder="Enter description (Optional)" id="" cols="30" rows="10">{{old('description')}}</textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default waves-effect waves-light m-r-10">Save</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/job/applications.blade.php
@extends('layouts.app')
@section('page_title')Job Applications @stop
@section('page')Job Applications @stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
@stop
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Applications for [ <span class="text-primary">{{ $offer->title ?? '' }}</span> ] </h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">USER ID</th>
                            <th>NAME</th>
                            <th>EMAIL</th>
                            <th class="text-center">CONTACT</th>
                            <th class="text-center">CV</th>
                            <th>APPLIED DATE</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($applications->count() > 0)
                            @foreach ($applications as $value)
                                <tr class="title">
                                    <td class="text-center">{{ $loop->iteration }}</td>
                                    <td class="text-center">
                                        {{ $value->app_user_id ?? '-' }}
                                    </td>
                                    <td>
                                        {{ $value->app_user->full_name ?? '-' }}
                                    </td>
                                    <td>{{ $value->app_user->email ?? '-' }}</td>
                                    <td class="text-center">{{ $value->app_user->phone ?? '-' }}</td>
                                    <td class="text-center">
                                        @if(isset($value->app_user->meta->cv))
                                            <a href="{{ asset(STATIC_DIR.'storage/'.$value->app_user->meta->cv) }}" target="_blank" class="btn btn-default btn-sm">View</a>
                                        @else
                                            -
                                        @endif
                                    </td>
                                    <td>{{ $value->created_at }}</td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9">No applications found.</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/js/dropify.min.js') }}"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/moment/moment.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script>
        // Date Picker
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });

        $(document).ready(function() {
            $('.dropify').dropify();
        });
    </script>
@stop

resources/views/job/edit-job-modal.blade.php
<div class="modal fade bs-example-modal-lg" id="edit-job" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel">Add Job / Intern</h4>
            </div>
            <form method="post" action="{{ route('job.update') }}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="job_id" id="edit_id">
                    {{--<div class="form-group">--}}
                        {{--<label for="input-file-now">Image</label>--}}
                        {{--<input type="file" name="image" id="input-file-now" class="dropify" />--}}
                    {{--</div>--}}
                    <div class="form-group">
                        <label for="input-file-now">Title</label>
                        <input type="text" name="title" id="edit_title" class="form-control" placeholder="Enter job title" />
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Deadline</label>
                        <div class="input-daterange input-group" id="date-range">
                            <input type="text" id="edit_deadline" class="form-control datepicker-autoclose" name="deadline" placeholder="Deadline" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="input-file-now">Job Location</label>
                        <input type="text" name="location" id="edit_location" class="form-control" placeholder="Enter job location" />
                        @error('location')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="input-file-now">Job Type</label>
                        <input type="text" class="form-control" readonly id="edit_job_type">
                        <select name="job_type" id="" class="form-control">
                            <option value="Internship">Internship</option>
                            <option value="Job">Job</option>
                        </select>
                    </div>
                    @if (Auth::check() AND Auth::user()->user_type=="admin")
                        <div class="form-group">
                            <label for="input-file-now">Provider</label>
                            <input type="text" class="form-control" readonly id="edit_provider">
                            
                            <select name="provider" id="" class="form-control">
                                <option value="Internship">--select--</option>
                                @foreach($providers as $value)
                                    <option value="{{ $value->id }}">{{ $value->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="input-file-now">Designation</label>
                        <input type="text" name="designation" id="edit_designation" class="form-control" placeholder="Enter designation" />
                        @error('designation')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="input-file-now">Description <span class="text-warning">( optional )</span></label>
                        <textarea name="description" class="form-control textarea_editor1" placeholder="Enter description (Optional)" id="" cols="30" rows="10">{{old('description')}}</textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                                <span class="text-sm text-danger">{{ $message }}</span>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default waves-effect waves-light m-r-10">Save</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/job/index.blade.php
@extends('layouts.app')
@section('page_title')Jobs / Interns @stop
@section('page')Jobs / Interns @stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/bootstrap-wysihtml5.css') }}" />
@stop
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Jobs / Intern Listing <a class="btn btn-sm btn-default pull-right" href="#add-job" data-toggle="modal">Add</a></h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th style="width: 400px;">TITLE</th>
                            <th class="text-center">DESCRIPTION</th>
                            <th class="text-center">DEADLINE</th>
                            <th class="text-center">TYPE</th>
                            <th class="text-center">DESIGNATION</th>
                            <th class="text-center">LOCATION</th>
                            <th class="text-center">APPLICATIONS</th>
                            <th class="text-center">PROVIDER</th>
                            <th class="text-center">CREATED AT</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($jobs->count() > 0)
                        @foreach ($jobs as $value)
                            <tr class="title">
                                <td class="text-center">{{ $loop->iteration }}</td>
                                <td>
                                    {{ $value->title ?? '' }}
                                    @if (!empty($value->deadline) AND $value->deadline->isPast())
                                        <span class="label label-danger">EXPIRED</span>
                                    @else
                                        <span class="label label-success">ACTIVE</span>
                                    @endif
                                    <div class="action">
                                        <a href="#edit-job" class="btn btn-sm btn-link text-blue" data-toggle="modal" data-data="{{ $value }}">Edit</a>
                                        <span class="vl"></span>
                                        <a href="" class="btn btn-sm btn-link text-danger">Trash</a>
                                    </div>
                                </td>

                                <td class="text-center">
                                    @if (!empty($value->description))
                                        <a class="btn btn-default btn-sm" href="#view-description" data-toggle="modal"
                                           data-title="{{ $value->title }}"
                                           data-data="{!! $value->description !!}">View</a>
                                    @else
                                        -
                                    @endif
                                </td>

                                
                                <td class="text-center">
                                    {{ $value->deadline->format('d M Y') }}
                                </td>

                                <td class="text-center"><span class="label label-primary">{{ $value->job_type }}</span></td>
                                <td class="text-center">{{ $value->designation }}</td>
                                <td class="text-center">    
                                     {{  $value->location  }}           
                                </td>
                                <td class="text-center"><a href="{{ route('job.get_applications',$value->id) }}">[ {{ $value->applications->count() }} ] application/s</a></td>
                                <td class="text-center">
                                    <a href="{{ route('profile.view',$value->provider) }}" calss="btn btn-link btn-sm">{{ $value->job_provider->name }}</a>
                                </td>
                                <td class="text-center">
                                    {{ $value->created_at->format('d M Y') }}
                                </td>
                            </tr>
                        @endforeach
                        @else
                            <tr>
                                <td colspan="7">No offers found. Click <a class="btn btn-sm btn-linkt" href="#add-job" data-toggle="modal">here </a>to add new job / intern.</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('job.add-job-modal')
    @include('job.edit-job-modal')
    @include('job.description-modal')
@endsection

@section('script')
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/js/dropify.min.js') }}"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/moment/moment.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/bootstrap-wysihtml5.js') }} "></script>
    <script>
        $(document).ready(function() {
            $('.textarea_editor').wysihtml5();

        });
        jQuery('.datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true,
            format: 'yyyy-mm-dd',
        });

        $(document).ready(function() {
            $('.dropify').dropify();
        });

        $('#view-description').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var title = button.data('title');
            var description = button.data('data');
            $(".job-title").html(title);
            $(".description").html(description);
        });
        $('#edit-job').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var data = button.data('data');

            $("#edit_id").val(data.id);
            $("#edit_title").val(data.title);
            $("#edit_deadline").val(data.deadline);
            $("#edit_job_type").val(data.job_type);
            $("#edit_provider").val(data.provider);
            $("#edit_designation").val(data.designation);
            $("#edit_location").val(data.location);

            // if($('#edit_job_type').val() == "job"){
                    
            // }

        });
    </script>
@stop