routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@update')->name('profile-update');

Route::group(['prefix' => 'university','as'=>'university.'], function () {
    Route::get('/', ['uses'=>'UniversityController@index','as'=>'index'])->middleware("can:university-list");
    Route::Post('/save', ['uses'=>'UniversityController@save','as'=>'save'])->middleware("can:university-list");
    Route::Post('/delete', ['uses'=>'UniversityController@delete','as'=>'delete'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'UniversityController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'faculty', 'as' => 'faculty.'],function(){
    Route::post('/delete',['uses' => 'FacultyController@delete','as' => 'delete'])->middleware("can:university-list");
    Route::post('/update',['uses' => 'FacultyController@update','as' => 'update'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'FacultyController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'offers','as'=>'offers.'], function () {
    Route::get('/', ['uses'=>'OfferController@index','as'=>'index'])->middleware("can:offer-list");
    Route::post('/save', ['uses'=>'OfferController@store','as'=>'save'])->middleware("can:offer-add");
    Route::get('/application/{offer_id}', ['uses'=>'OfferController@get_applications','as'=>'get_applications'])->middleware("can:offer-applications-list");
    Route::post('/edit', ['uses'=>'OfferController@edit','as'=>'edit'])->middleware("can:offer-edit");

    //Admin Routes
    Route::post('/delete', ['uses'=>'OfferController@delete','as'=>'delete'])->middleware("can:offer-delete");
    Route::get('/approve/{id}', ['uses'=>'OfferController@approve','as'=>'approve']);
    Route::get('/reject/{id}', ['uses'=>'OfferController@reject','as'=>'reject']);
//    Route::get('/edit/offer/{id}/{action}', ['uses'=>'OfferController@canEditOffer','as'=>'can-edit-offer']);
});

Route::group(['prefix' => 'files','as'=>'files.'], function () {
    Route::get('/', ['uses'=>'NoteController@index','as'=>'index']);

    Route::group(['prefix' => 'notes','as'=>'notes.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'NoteController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'NoteController@delete_file','as'=>'delete']);
        Route::post('/upload', ['uses'=>'NoteController@upload_files','as'=>'upload']);
        Route::get('list_ajax/{faculty_id}', 'NoteController@files_ajax');
    });

    Route::group(['prefix' => 'solutions','as'=>'solutions.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'SolutionController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'SolutionController@delete','as'=>'delete']);
        Route::post('/upload', ['uses'=>'SolutionController@upload','as'=>'upload']);
    });

});

Route::group(['prefix' => 'profile','as'=>'profile.'], function () {
    Route::get('/{id}', ['uses'=>'UserController@view_profile','as'=>'view']);
});


Route::group(['prefix' => 'user','as'=>'user.'], function () {
    Route::get('/list', ['uses'=>'UserController@index','as'=>'index']);
    Route::post('/register', ['uses'=>'UserController@register','as'=>'register']);
    Route::get('/admin', ['uses'=>'UserController@admin_index','as'=>'index.admin']);
    Route::get('/permission', ['uses'=>'UserController@getPermission','as'=>'permission']);
    Route::Post('/permission/add', ['uses'=>'UserController@savePermission','as'=>'permission.add']);
    Route::get('/assign_permission/{id}', ['uses'=>'UserController@assign_permission', 'as'=>'assign_permission']);
    Route::post('/assign_permission/store', ['uses'=>'UserController@assign_permission_store', 'as'=>'assign_permission_store']);
    Route::post('/permission_view', ['uses'=>'UserController@permission_view', 'as'=>'permission_view']);
});

Route::group(['prefix' => 'job','as'=>'job.'], function () {
    Route::get('/', ['uses'=>'JobController@index','as'=>'index']);
    Route::post('/save', ['uses'=>'JobController@store','as'=>'save']);
    Route::get('/application/{job_id}', ['uses'=>'JobController@get_applications','as'=>'get_applications']);
    Route::post('/update', ['uses'=>'JobController@update','as'=>'update']);
});


Route::get('/setup', ["uses"=>'SetupController@setup'])->name('setup');
Route::post('/setup/run', ["uses"=>'SetupController@setup_run'])->name('setup.run');

app/University.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class University extends Model
{
    protected $primaryKey = 'u_id';

    public function faculty()
    {
        return $this->hasMany(Faculty::class,'university_id');
    }

    public function college()
    {
        return $this->hasMany(College::class,'university_id');
    }


}

app/Http/Controllers/Api/UniversityController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helper\Tools;
use App\University;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UniversityController extends Controller
{
    public function getAllUniversity()
    {
        $university = University::with('faculty')->where('status',1)->get();

        $responseData = Tools::setResponse(false,'University Listing Successfull',$university,'');
        return response()->json($responseData);
    }

    public function getFacultyByUniversityId(){
        ///check if id is sent or not.
        if(!isset($_GET['u_id'])){
            if(empty($_GET['u_id'])){
                $responseData = Tools::setResponse(true,'Missing Parameter','','');
                return response()->json($responseData);
            }
        }

        $university = University::where('u_id',$_GET['u_id'])->with('faculty','college','faculty.notes')->first();

        $responseData = Tools::setResponse(false,'Faculty listing with its related notes by University Id  successfull',$university,'');
        return response()->json($responseData);

    }

}

app/Http/Controllers/UniversityController.php
<?php

namespace App\Http\Controllers;

use App\Faculty;
use App\University;
use Illuminate\Http\Request;

class UniversityController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['university'] = University::all();
        $data['faculty'] = Faculty::with('university')->orderBy('university_id')->get();
        return view('university.index',$data);
    }

    public function save(Request $request)
    {
        if ($request->type=='university') {
            $this->validate($request,[
                'name' => 'required|max:200'
            ]);
            $university = new University();

            if ($request->hasFile('logo')){
                $path = $request->file('logo')->store('university', 'public');
                $university->logo = $path;
            }
            $university->name = $request->name;
            $university->status = 0;
            $university->save();
        }
        elseif ($request->type=='faculty'){
            $this->validate($request,[
                'university_id' => 'required',
                'title' => 'required|max:200',
                'course_type' => 'required|max:200',
                'count' => 'required',
            ]);
            $faculty = new Faculty();
            $faculty->university_id = $request->university_id;
            $faculty->title = $request->title;
            $faculty->course_type = $request->course_type;
            $faculty->count = $request->count;
            $faculty->save();
        }

        return redirect()->back();
    }

    public function change_status($id)
    {
        $uni = University::find($id);
        if ($uni->status==1){
            $uni->status = 0;
        }else{
            $uni->status = 1;
        }
        $uni->save();
        return redirect()->back();
    }

    public function delete(Request $request){
        $file = University::where('u_id',$request->id)->first();
        \Storage::delete('public/'.$file->logo);
        $file->delete();
        $flashMessage = [
            'heading'=>'success',
            'type'=>'success',
            'message'=>'University deleted successfully.'
        ];
        \Session::flash('flash_message', $flashMessage);
        return json_encode(array('success'=>'true'));
    }
}

resources/views/university/add-faculty-modal.blade.php
<div class="modal fade bs-example-modal-lg" id="add-faculty" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel">Add Faculty</h4>
            </div>
            <form method="post" action="{{ route('university.save') }}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="type" value="faculty" id="">
                    <div class="form-group">
                        <label for="input-file-now-custom-2">University</label>
                        <select class="form-control" name="university_id" id="">
                            <option value="">Select One</option>
                            @foreach($university as $value)
                                <option value="{{ $value->u_id }}">{{ $value->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Faculty Title</label>
                        <input type="text" name="title" class="form-control" id="" placeholder="Faculty Title">
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Course Type</label>
                        <select name="course_type" id="" class="form-control">
                            <option value="">Select One</option>
                            <option value="year">Year</option>
                            <option value="semester">Semester</option>
                        </select>
                        @error('course_type')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Number of Year/Semester</label>
                        <input type="number" name="count" class="form-control" id="" placeholder="Number of Year/Semester">
                        @error('count')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-default waves-effect waves-light m-r-10">Reset</button>
                    <button type="submit" class="btn btn-default waves-effect waves-light m-r-10">Save</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/university/add-university-modal.blade.php
<div class="modal fade bs-example-modal-lg" id="add-university" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel">Add University</h4>
            </div>
            <form method="post" action="{{ route('university.save') }}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="type" value="university" id="">
                    <div class="form-group">
                        <label for="input-file-now">University Logo</label>
                        <input type="file" name="logo" id="input-file-now" class="dropify" />
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">University Name</label>
                        <input type="text" name="name" class="form-control" id="" placeholder="University Name">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-default waves-effect waves-light m-r-10">Reset</button>
                    <button type="submit" class="btn btn-default waves-effect waves-light m-r-10">Save</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

{{--modal for edit the university--}}
<div class="modal fade bs-example-modal-lg" id="edit-university" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel">Edit University</h4>
            </div>
            <form method="post" action="{{ route('university.save') }}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="type" value="university" id="">
                    <div class="form-group">
                        <label for="input-file-now">University Logo</label>
                        <input type="file" name="logo" id="input-file-now" class="dropify" src="{{asset(STATIC_DIR.'university/ujBcIY1dzcUGDJxkLkC4F5DqFnsBIlEqetwHJvxG.jpeg" ')}}"/>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">University Name</label>
                        <input type="text" name="name" class="form-control" id="university_name" placeholder="University Name">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default waves-effect waves-light m-r-10">Save</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

{{--end edit modal university--}}

resources/views/university/delete-faculty-modal.blade.php
<div class="modal fade bs-example-modal-sm" id="delete_faculty" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="mySmallModalLabel"><i class="mdi mdi-information text-danger fa-fw"></i>Delete</h4> </div>
            <div class="modal-body">
                Are you sure you want to delete Faculty?
            </div>
            <input type="hidden" name="" id="faculty_id">
            <div class="modal-footer">
                <button type="button" class="btn btn-danger green confirm" id="confirm"> Delete
                </button>
                <button type="button" class="btn btn-defult" data-dismiss="modal">
                    Cancel
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/university/edit-faculty-modal.blade.php
<div class="modal fade bs-example-modal-lg" id="edit-faculty" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel">Edit Faculty</h4>
            </div>
            <form method="post" action="{{ route('faculty.update') }}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="faculty_id" id="faculty_id">
                    <div class="form-group">
                        <label for="input-file-now-custom-2">University</label>
                        <select class="form-control" name="university_id" id="university_id">
                            <option value="">Select One</option>
                            @foreach($university as $value)
                                <option value="{{ $value->u_id }}">{{ $value->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Faculty Title</label>
                        <input type="text" name="title" class="form-control" id="title" placeholder="Faculty Title">
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Course Type</label>
                        <select name="course_type" id="course_type" class="form-control">
                            <option value="">Select One</option>
                            <option value="year">Year</option>
                            <option value="semester">Semester</option>
                        </select>
                        @error('course_type')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Number of Year/Semester</label>
                        <input type="number" name="count" class="form-control" id="count" placeholder="Number of Year/Semester">
                        @error('count')
                        <span class="invalid-feedback" role="alert">
                                    <span class="text-sm text-danger">{{ $message }}</span>
                                </span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default waves-effect waves-light m-r-10">Update</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/university/index.blade.php
@extends('layouts.app')
@section('page_title')University @stop
@section('page')University @stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
@stop
@section('content')
    <div class="white-box">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="box-title m-b-2">university list <a class=" btn btn-sm btn-default pull-right" href="#add-university" data-toggle="modal">add</a></h3>
                <div class="table-responsive">
                    <table class="table table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th class="text-center">NAME</th>
                            <th class="text-center">LOGO</th>
                            <th class="text-center" style="width: 200px;">STATUS</th>
                            <th style="width: 150px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($university as $value)
                            <tr>
                                <td class="text-center">{{ $value->name ?? '' }}</td>
                                <td class="text-center">
                                    @if (!empty($value->logo))
                                        <img src="{{ asset(STATIC_DIR.'storage/'.$value->logo) }}" alt="" width="70">
                                    @else
                                        <i class="mdi mdi-image"></i>
                                    @endif
                                </td>
                                <td class="text-center">
                                    @if($value->status==1)
                                        <span class="label label-success">ENABLED</span>
                                        <a href="{{ route('university.change_status',$value->u_id) }}" class="btn btn-link btn-sm">Disable?</a>
                                    @else
                                        <span class="label label-danger">DISABLED</span>
                                        <a href="{{ route('university.change_status',$value->u_id) }}" class="btn btn-link btn-sm">Enable?</a>
                                    @endif

                                </td>
                                <td class="text-center">
                                    <a href="#edit-university" data-id="{{$value->u_id}}" data-name="{{$value->name}}" data-logo="{{$value->logo}}"  data-toggle="modal" class="btn btn-sm btn-link action-primary"><i class="mdi mdi-pencil-box-outline"></i></a>
                                    <span class="vl"></span>
                                    <a href="#delete_university" data-id="{{$value->u_id}}" data-toggle="modal" class="btn btn-sm btn-link action-danger text-danger"><i class="mdi mdi-delete-forever"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-md-6">
                <h3 class="box-title m-b-2">Faculty List <a class=" btn btn-sm btn-default pull-right" href="#add-faculty" data-toggle="modal">add</a></h3>
                <div class="table-responsive">
                    <table class="table table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th class="text-center">TITLE</th>
                            <th class="text-center">UNIVERSITY</th>
                            <th class="text-center">COURSE TYPE</th>
                            <th class="text-center">SEM / YEAR</th>
                            <th class="text-center">STATUS</th>
                            <th style="width: 150px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($faculty as $value)
                            <tr>
                                <td class="text-center">{{ $value->title ?? '' }}</td>
                                <td class="text-center">
                                    <span class="label label-default text-dark">{{ $value->university->name }}</span>
                                </td>
                                <td class="text-center">{{ $value->course_type }}</td>
                                <td class="text-center">{{ $value->count }}</td>
                                <td class="text-center">
                                    @if($value->status==1)
                                        <span class="label label-success">ENABLED</span>
                                        <a href="{{ route('faculty.change_status',$value->f_id) }}" class="btn btn-link btn-sm">Disable?</a>
                                    @else
                                        <span class="label label-danger">DISABLED</span>
                                        <a href="{{ route('faculty.change_status',$value->f_id) }}" class="btn btn-link btn-sm">Enable?</a>
                                    @endif

                                </td>
                                <td class="text-center">
                                    <a href="#edit-faculty" data-data="{{$value}}" data-toggle="modal" class="btn btn-sm btn-link action-primary"><i class="mdi mdi-pencil-box-outline"></i></a>
                                    <span class="vl"></span>
                                    <a href="#delete_faculty" data-id="{{$value->f_id}}" data-toggle="modal" class="btn btn-sm btn-link action-danger text-danger"><i class="mdi mdi-delete-forever"></i></a>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @include('university.add-university-modal')
    @include('university.add-faculty-modal')
    @include('university.edit-faculty-modal')

    @include('university.delete-university-modal')
    @include('university.delete-faculty-modal')

@endsection

@section('script')
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/js/dropify.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.dropify').dropify();
        });

        // AJAX FILE UNIVERSITY

        // UNIVERSITY DELETE
        $('#delete_university').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            $("#university_id").val(id);
        });

        $('#delete_university').find('.modal-footer #confirm').on('click', function () {
            var id = $("#university_id").val();
            $.ajax({
                type: "POST",
                url: "{{ route('university.delete') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + id,
                success: function (msg) {
                    console.log(msg.success);
                    $("#confirmDelete").modal("hide");
                    // window.location.reload();
                }
            });
        });

        // UNIVERSITY EDIT
        $('#edit-university').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            var name = button.data('name');
            var logo = button.data('logo');

            $("#university_id").val(id);
            $("#university_name").val(name);
            $("#university_logo").val(logo);

        });

        $('#delete_university').find('.modal-footer #confirm').on('click', function () {
            var id = $("#university_id").val();
            $.ajax({
                type: "POST",
                url: "{{ route('university.delete') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + id,
                success: function (msg) {
                    console.log(msg.success);
                    $("#confirmDelete").modal("hide");
                    window.location.reload();
                }
            });
        });

        // AJAX FILE FACULTY DELETE
        $('#delete_faculty').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            $("#faculty_id").val(id);
        });

        $('#delete_faculty').find('.modal-footer #confirm').on('click', function () {
            var id = $("#faculty_id").val();
            $.ajax({
                type: "POST",
                url: "{{ route('faculty.delete') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + id,
                success: function (msg) {
                    console.log(msg.success);
                    $("#confirmDelete").modal("hide");
                    window.location.reload();
                }
            });
        });

        // EDIT FACULTY
        $('#edit-faculty').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var data = button.data('data');
           console.log(data)
            $('#faculty_id').val(data.f_id)
            $('#title').val(data.title)
            $('#count').val(data.count)
            $('#university_id').val(data.university_id)
            $('#course_type').val(data.course_type)
        });
    </script>
@stop