routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@update')->name('profile-update');

Route::group(['prefix' => 'university','as'=>'university.'], function () {
    Route::get('/', ['uses'=>'UniversityController@index','as'=>'index'])->middleware("can:university-list");
    Route::Post('/save', ['uses'=>'UniversityController@save','as'=>'save'])->middleware("can:university-list");
    Route::Post('/delete', ['uses'=>'UniversityController@delete','as'=>'delete'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'UniversityController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'faculty', 'as' => 'faculty.'],function(){
    Route::post('/delete',['uses' => 'FacultyController@delete','as' => 'delete'])->middleware("can:university-list");
    Route::post('/update',['uses' => 'FacultyController@update','as' => 'update'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'FacultyController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'offers','as'=>'offers.'], function () {
    Route::get('/', ['uses'=>'OfferController@index','as'=>'index'])->middleware("can:offer-list");
    Route::post('/save', ['uses'=>'OfferController@store','as'=>'save'])->middleware("can:offer-add");
    Route::get('/application/{offer_id}', ['uses'=>'OfferController@get_applications','as'=>'get_applications'])->middleware("can:offer-applications-list");
    Route::post('/edit', ['uses'=>'OfferController@edit','as'=>'edit'])->middleware("can:offer-edit");

    //Admin Routes
    Route::post('/delete', ['uses'=>'OfferController@delete','as'=>'delete'])->middleware("can:offer-delete");
    Route::get('/approve/{id}', ['uses'=>'OfferController@approve','as'=>'approve']);
    Route::get('/reject/{id}', ['uses'=>'OfferController@reject','as'=>'reject']);
//    Route::get('/edit/offer/{id}/{action}', ['uses'=>'OfferController@canEditOffer','as'=>'can-edit-offer']);
});

Route::group(['prefix' => 'files','as'=>'files.'], function () {
    Route::get('/', ['uses'=>'NoteController@index','as'=>'index']);

    Route::group(['prefix' => 'notes','as'=>'notes.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'NoteController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'NoteController@delete_file','as'=>'delete']);
        Route::post('/upload', ['uses'=>'NoteController@upload_files','as'=>'upload']);
        Route::get('list_ajax/{faculty_id}', 'NoteController@files_ajax');
    });

    Route::group(['prefix' => 'solutions','as'=>'solutions.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'SolutionController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'SolutionController@delete','as'=>'delete']);
        Route::post('/upload', ['uses'=>'SolutionController@upload','as'=>'upload']);
    });

});

Route::group(['prefix' => 'profile','as'=>'profile.'], function () {
    Route::get('/{id}', ['uses'=>'UserController@view_profile','as'=>'view']);
});


Route::group(['prefix' => 'user','as'=>'user.'], function () {
    Route::get('/list', ['uses'=>'UserController@index','as'=>'index']);
    Route::post('/register', ['uses'=>'UserController@register','as'=>'register']);
    Route::get('/admin', ['uses'=>'UserController@admin_index','as'=>'index.admin']);
    Route::get('/permission', ['uses'=>'UserController@getPermission','as'=>'permission']);
    Route::Post('/permission/add', ['uses'=>'UserController@savePermission','as'=>'permission.add']);
    Route::get('/assign_permission/{id}', ['uses'=>'UserController@assign_permission', 'as'=>'assign_permission']);
    Route::post('/assign_permission/store', ['uses'=>'UserController@assign_permission_store', 'as'=>'assign_permission_store']);
    Route::post('/permission_view', ['uses'=>'UserController@permission_view', 'as'=>'permission_view']);
});

Route::group(['prefix' => 'job','as'=>'job.'], function () {
    Route::get('/', ['uses'=>'JobController@index','as'=>'index']);
    Route::post('/save', ['uses'=>'JobController@store','as'=>'save']);
    Route::get('/application/{job_id}', ['uses'=>'JobController@get_applications','as'=>'get_applications']);
    Route::post('/update', ['uses'=>'JobController@update','as'=>'update']);
});


Route::get('/setup', ["uses"=>'SetupController@setup'])->name('setup');
Route::post('/setup/run', ["uses"=>'SetupController@setup_run'])->name('setup.run');

app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $dates = ['start_date','end_date'];
    public function author()
    {
        return $this->belongsTo(User::class,'created_by');
    }

    public function offer()
    {
        return $this->belongsTo(User::class,'offer_by');
    }

    public function application()
    {
        return $this->hasMany(OfferApplication::class,'offer_id');
    }
}

app/Http/Controllers/Api/OfferController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helper\Tools;
use App\Offer;
use App\OfferApplication;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OfferController extends Controller
{
    public function offerListing()
    {
        $now = date('Y-m-d H:i:s');
        $data = Offer::where('is_approved',1)->where('end_date','>', $now)->orWhereNull('end_date')->with('offer')->get();
        $responseData = Tools::setResponse(false,'offer_listed_successfully',$data,'');

        return response()->json($responseData);
    }

    public function apply(Request $request)
    {
        $this->validate($request, [
            'offer_id' => 'required',
            'app_user_id' => 'required'
        ]);

        $offer = Offer::find($request->offer_id);
        if (is_null($offer)){
            $responseData = Tools::setResponse(true,'offer_not_found','','');
        }else{
            $check_application = OfferApplication::where('app_user_id', $request->app_user_id)->where('offer_id', $request->offer_id)->get();
            if ($check_application->count() > 0){
                $responseData = Tools::setResponse(true,'already_applied','','');
            }else{
                $apply = new OfferApplication();
                $apply->app_user_id = $request->app_user_id;
                $apply->offer_id = $offer->id;
                $apply->save();
                $responseData = Tools::setResponse(false,'offer_applied_successfully','','');
            }
        }

        return response()->json($responseData);
    }
}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use App\OfferApplication;
use App\User;
use Illuminate\Http\Request;
use Auth;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;

class OfferController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['users'] = User::where('user_type', 'user')->get();
        $data['offers'] = Offer::with(['author','offer','application'])->get();
        return view('offers.index',$data);

        // FOR ADMIN
//        if (Auth::user()->user_type=='admin'){
//            $data['users'] = User::where('user_type', 'user')->get();
//            $data['offers'] = Offer::with(['author','offer','application'])->get();
//            return view('offers.index-admin',$data);
//        }
//        // FOR USER
//        elseif (Auth::user()->user_type=='user'){
//            $data['offers'] = Offer::where('offer_by',Auth::user()->id)->with(['offer','application'])->get();
//            return view('offers.index',$data);
//        }
//        else{
//            abort(403);
//        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'user_type' => 'required',
            'title' => 'required|max:255',
//            'offer_by' => 'required'
        ]);

        $offer = new Offer();
        $offer->title = $request->title;

        if(!empty($request->start)){
            $offer->start_date = date("Y-m-d H:i:s",strtotime($request->start));
        }

        if(!empty($request->end)){
            $offer->end_date = date("Y-m-d H:i:s",strtotime($request->end));
        }

        $offer->description = $request->description;
        if ($request->hasFile('image')) {
            $offer->image = $request->file('image')->store('offers', 'public');
        }
        if (Auth::user()->user_type=='user'){
            $offer->offer_by = Auth::user()->id;
            $offer->is_approved = 0;
        }else{
            $offer->offer_by = $request->offer_by;
            $offer->is_approved = 1;
        }
        $offer->created_by = Auth::user()->id;
        $offer->save();

        return redirect()->back();
    }

    public function edit(Request $request){
        $request->validate([
            'title' => 'required|max:255',
        ]);

        $offer = Offer::find($request->offer_id);
        $offer->title = $request->title;

        if(!empty($request->start)){
            $offer->start_date = date("Y-m-d H:i:s",strtotime($request->start));
        }

        if(!empty($request->end)){
            $offer->end_date = date("Y-m-d H:i:s",strtotime($request->end));
        }

        if(!empty($request->description)){
            $offer->description = $request->description;
        }

        //if new image is uploaded.
        if(isset($request->image)){
            Storage::delete('public/'.$offer->image);
            $offer->image = $request->file('image')->store('offers', 'public');
        }
        $offer->updated_at = date('Y-m-d H:i:s');
        $offer->save();

        return redirect()->back();
    }

    public function approve($id){
        $offer = Offer::find($id);
        $offer->is_approved = 1;
        $offer->save();

        return redirect()->back();
    }

    public function reject($id){
        $offer = Offer::find($id);
        $offer->is_approved = 2;
        $offer->save();

        return redirect()->back();
    }

    public function canEditOffer($id,$action){
        $offer = Offer::find($id);

        if($action == "can_edit"){
            $offer->can_edit = 1;
        }
        else{
            $offer->can_edit = 0;
        }
        $offer->save();


        return redirect()->back();
    }

    public function delete(Request $request){
        $offer = Offer::find($request->id);
        Storage::delete('public/'.$offer->image);
        $offer->delete();
    }

    // APPLICATIONS

    public function get_applications($offer_id)
    {
        $data['offer'] = Offer::find($offer_id);
        $data['applications'] = OfferApplication::where('offer_id', $offer_id)->with('app_user')->get();

        return view('offers.applications', $data);
    }
}

resources/views/offers/description-modal.blade.php
<div class="modal fade bs-example-modal-lg" id="view-description" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myLargeModalLabel"><span class="offer-title"></span></h4>
            </div>
            <div class="modal-body">
                <span class="description"></span>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/offers/index-user-DELETE.blade.php
@extends('layouts.app')
@section('page_title')Offers @stop
@section('page')Offers @stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/bootstrap-wysihtml5.css') }}" />
@stop
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">My Offers </h3>
                <div class="table-responsive"><a class="btn btn-sm btn-default pull-right" href="#add-offer" data-toggle="modal">Add</a>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th style="width: 350px;">TITLE</th>
                            <th>IMAGE</th>
                            <th>START DATE</th>
                            <th>END DATE</th>
                            <th>VALIDITY</th>
                            <th>STATUS</th>
                            <th>DESCRIPTION</th>
                            <th>APPLICATIONS</th>
                            <th>OFFERED BY</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($offers->count() > 0)
                        @foreach ($offers as $value)
                            <tr class="title">
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    {{ $value->title ?? '' }}
                                    <div class="action">
                                        @if ($value->can_edit==1)
                                            <a class="btn btn-sm btn-link text-blue" href="#edit-offer"
                                               data-toggle="modal" data-id="{{$value->id}}"
                                               data-title="{{$value->title}}" data-description="{{$value->description}}"
                                               data-start_date="{{$value->start_date}}" data-end_date="{{$value->end_date}}">Edit</a>
                                        @else
                                            <a href="" class="btn btn-sm btn-link text-blue">request edit</a>
                                        @endif
                                        <span class="vl"></span>
                                        <a href="#delete_offer" data-id="{{$value->id}}" data-toggle="modal" class="btn btn-sm btn-link text-danger">Trash</a>
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ asset(STATIC_DIR.'storage/'.$value->image) }}" target="_blank"><i class="mdi mdi-image"></i></a>
                                </td>
                                <td>@if(!empty($value->start_date)) {{ $value->start_date->format('d M Y') }} @else - @endif</td>
                                <td>@if(!empty($value->end_date)) {{ $value->end_date->format('d M Y') }} @else - @endif</td>
                                <td>
                                    @if (!empty($value->end_date) AND $value->end_date->isPast())
                                        <span class="label label-danger">EXPIRED</span>
                                    @else
                                        <span class="label label-success">ACTIVE</span>
                                    @endif
                                </td>
                                <td>
                                    @if ($value->is_approved==0)
                                        <span class="label label-danger">PENDING</span>
                                    @elseif ($value->is_approved==1)
                                        <span class="label label-danger">APPROVED</span>
                                    @else
                                        <span class="label label-success">REJECTED</span>
                                    @endif
                                </td>
                                <td>{{ $value->description ?? '' }}</td>
                                <td><a href="{{ route('offers.get_applications',$value->id) }}">[ {{ $value->application->count() }} ] application/s</a></td>
                                <td><a href="{{ route('profile.view',$value->offer_by) }}" calss="btn btn-link btn-sm">{{ $value->offer->name }}</a></td>
                            </tr>
                        @endforeach
                        @else
                            <tr>
                                <td colspan="9">No offers found. Click <a class="btn btn-sm btn-linkt" href="#add-offer" data-toggle="modal">here </a>to add new offer.</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('offers.add-offer-modal')
    @include('offers.edit-offer-modal')
    @include('offers.delete-offer-modal')

@endsection

@section('script')
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/js/dropify.min.js') }}"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/moment/moment.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/bootstrap-wysihtml5.js') }} "></script>
    <script>
        // Date Picker
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });

        $(document).ready(function() {
            $('.dropify').dropify();
            $('.textarea_editor').wysihtml5();
        });

        // OFFER EDIT
        $('#edit-offer').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            var title = button.data('title');
            var description = button.data('description');
            var start_date = button.data('start_date');
            var end_date = button.data('end_date');

            var modal = $(this)

            if(description != ''){
                modal.find('.modal-body #description').val(description)
            }

            if(start_date != ''){
                modal.find('.modal-body #start_date').val(start_date)
            }

            if(end_date != ''){
                modal.find('.modal-body #end_date').val(end_date)
            }

            modal.find('.modal-body #offer_id').val(id)
            modal.find('.modal-body #title').val(title)
            $("#offer_id").val(id);
        });

        // OFFER DELETE
        $('#delete_offer').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            $("#offer_id").val(id);
        });

        $('#delete_offer').find('.modal-footer #confirm').on('click', function () {
            var id = $("#offer_id").val();
            $.ajax({
                type: "POST",
                url: "{{ route('offers.delete') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + id,
                success: function (msg) {
                    // console.log(msg.success);
                    $("#delete_offer").modal("hide");
                    window.location.reload();
                }
            });
        });
    </script>
@stop

resources/views/offers/index.blade.php
@extends('layouts.app')
@section('page_title')Offers @stop
@section('page')Offers @stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/bootstrap-wysihtml5.css') }}" />
@stop
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">

                <h3 class="box-title m-b-0">offers list  @can('offer-add')<a class="btn btn-sm btn-default pull-right" href="#add-offer-admin" data-toggle="modal">add</a> @endcan</h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th style="width: 350px;">TITLE</th>
                            <th class="text-center">IMAGE</th>
                            <th class="text-center">START DATE</th>
                            <th class="text-center">END DATE</th>
                            <th class="text-center">DESCRIPTION</th>
                            <th class="text-center">VALIDITY</th>
                            <th class="text-center">APPLICATIONS</th>
                            @if (Auth::user()->user_type=='admin')
                                <th>OFFERED BY</th>
                                <th>CREATED BY</th>
                            @endif
                        </tr>
                        </thead>
                        <tbody>
                        @if($offers->count() > 0)
                            @foreach ($offers as $value)
                                <tr class="title">
                                    <td class="text-center">{{ $loop->iteration }}</td>
                                    <td>
                                        {{ $value->title ?? '' }}
                                        @if ($value->is_approved==0)
                                            <span class="label label-warning">PENDING</span>
                                        @elseif ($value->is_approved==1)
                                            <span class="label label-success">APPROVED</span>
                                        @else
                                            <span class="label label-danger">REJECTED</span>
                                        @endif
                                        <div class="action">
                                            @if (Auth::user()->user_type=='admin')
                                                <a href="{{route('offers.approve',$value->id)}}" class="btn btn-sm btn-link text-blue">Approve</a>
                                                <span class="vl"></span>
                                                <a href="{{route('offers.reject',$value->id)}}" class="btn btn-sm btn-link text-blue">Reject</a>
                                                <span class="vl"></span>
                                            @endif
                                            @can('offer-edit')
                                                <a class="btn btn-sm btn-link text-blue" href="#edit-offer"
                                                   data-toggle="modal" data-id="{{$value->id}}"
                                                   data-title="{{$value->title}}" data-description="{!! $value->description !!}"
                                                   data-start_date="{{$value->start_date}}" data-end_date="{{$value->end_date}}">Edit</a>
                                                <span class="vl"></span>
                                            @endcan
                                            @can('offer-delete')
                                                <a href="#delete_offer" data-id="{{$value->id}}" data-toggle="modal" class="btn btn-sm btn-link text-danger">Delete</a>
                                            @endcan

                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ asset(STATIC_DIR.'storage/'.$value->image) }}" target="_blank"><i class="mdi mdi-image"></i></a>
                                    </td>
                                    <td class="text-center">@if(!empty($value->start_date)) {{ $value->start_date->format('d M Y') }} @else - @endif</td>
                                    <td class="text-center">@if(!empty($value->end_date)) {{ $value->end_date->format('d M Y') }} @else - @endif</td>
                                    <td class="text-center">
                                        @if (!empty($value->description))
                                            <a class="btn btn-default btn-sm" href="#view-description" data-toggle="modal"
                                               data-title="{{ $value->title }}"
                                               data-data="{!! $value->description !!}">View</a>
                                        @else
                                            -
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if (!empty($value->end_date) AND $value->end_date->isPast())
                                            <span class="label label-danger">EXPIRED</span>
                                        @else
                                            <span class="label label-success">ACTIVE</span>
                                        @endif
                                    </td>
                                    <td class="text-center"><a href="{{ route('offers.get_applications',$value->id) }}">[ {{ $value->application->count() }} ] application/s</a></td>
                                    @if (Auth::user()->user_type=='admin')
                                        <td><a href="{{ route('profile.view',$value->offer_by) }}" calss="btn btn-link btn-sm">{{ $value->offer->name }}</a></td>
                                        <td><a href="{{ route('profile.view',$value->created_by) }}" calss="btn btn-link btn-sm">{{ $value->author->name }}</a></td>
                                    @endif
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="10">No offers found. Click <a class="btn btn-sm btn-linkt" href="#add-offer-admin" data-toggle="modal">here </a>to add new offer.</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('offers.add-offer-modal-admin')
    @include('offers.delete-offer-modal')
    @include('offers.edit-offer-modal')
    @include('offers.description-modal')
@endsection

@section('script')
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/dropify/dist/js/dropify.min.js') }}"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/moment/moment.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/html5-editor/bootstrap-wysihtml5.js') }} "></script>
    <script>
        // Date Picker
        jQuery('#date-range').datepicker({
            toggleActive: true
        });
        // Daterange picker
        $('.input-daterange-datepicker').daterangepicker({
            buttonClasses: ['btn', 'btn-sm'],
            applyClass: 'btn-danger',
            cancelClass: 'btn-inverse'
        });

        $(document).ready(function() {
            $('.dropify').dropify();
            $('.textarea_editor').wysihtml5();
            $('.textarea_editor1').wysihtml5();
        });

        @if($errors->count() > 0 )
        $("#add-offer-admin").modal("show");
        @endif

        // OFFER DELETE
        $('#delete_offer').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            $("#offer_id").val(id);
        });

        $('#delete_offer').find('.modal-footer #confirm').on('click', function () {
            var id = $("#offer_id").val();
            $.ajax({
                type: "POST",
                url: "{{ route('offers.delete') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + id,
                success: function (msg) {
                    // console.log(msg.success);
                    $("#delete_offer").modal("hide");
                    window.location.reload();
                }
            });
        });

        $('#edit-offer').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('id');
            var title = button.data('title');
            var description = button.data('description');
            var start_date = button.data('start_date');
            var end_date = button.data('end_date');
            var modal = $(this)

            modal.find('.modal-body .textarea_editor1').val(description)
            modal.find('.modal-body #start_date').val(start_date)
            modal.find('.modal-body #end_date').val(end_date)
            modal.find('.modal-body #offer_id').val(id)
            modal.find('.modal-body #title').val(title)
            $("#offer_id").val(id);
        });

        // VIEW DESCRIPTION
        $('#view-description').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var title = button.data('title');
            var description = button.data('data');
            $(".offer-title").html(title);
            $(".description").html(description);
        });
    </script>
@stop