routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/update', 'ProfileController@update')->name('profile-update');

Route::group(['prefix' => 'university','as'=>'university.'], function () {
    Route::get('/', ['uses'=>'UniversityController@index','as'=>'index'])->middleware("can:university-list");
    Route::Post('/save', ['uses'=>'UniversityController@save','as'=>'save'])->middleware("can:university-list");
    Route::Post('/delete', ['uses'=>'UniversityController@delete','as'=>'delete'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'UniversityController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'faculty', 'as' => 'faculty.'],function(){
    Route::post('/delete',['uses' => 'FacultyController@delete','as' => 'delete'])->middleware("can:university-list");
    Route::post('/update',['uses' => 'FacultyController@update','as' => 'update'])->middleware("can:university-list");
    Route::get('/change_status/{id}', ['uses'=>'FacultyController@change_status','as'=>'change_status'])->middleware("can:university-list");
});

Route::group(['prefix' => 'offers','as'=>'offers.'], function () {
    Route::get('/', ['uses'=>'OfferController@index','as'=>'index'])->middleware("can:offer-list");
    Route::post('/save', ['uses'=>'OfferController@store','as'=>'save'])->middleware("can:offer-add");
    Route::get('/application/{offer_id}', ['uses'=>'OfferController@get_applications','as'=>'get_applications'])->middleware("can:offer-applications-list");
    Route::post('/edit', ['uses'=>'OfferController@edit','as'=>'edit'])->middleware("can:offer-edit");

    //Admin Routes
    Route::post('/delete', ['uses'=>'OfferController@delete','as'=>'delete'])->middleware("can:offer-delete");
    Route::get('/approve/{id}', ['uses'=>'OfferController@approve','as'=>'approve']);
    Route::get('/reject/{id}', ['uses'=>'OfferController@reject','as'=>'reject']);
//    Route::get('/edit/offer/{id}/{action}', ['uses'=>'OfferController@canEditOffer','as'=>'can-edit-offer']);
});

Route::group(['prefix' => 'files','as'=>'files.'], function () {
    Route::get('/', ['uses'=>'NoteController@index','as'=>'index']);

    Route::group(['prefix' => 'notes','as'=>'notes.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'NoteController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'NoteController@delete_file','as'=>'delete']);
        Route::post('/upload', ['uses'=>'NoteController@upload_files','as'=>'upload']);
        Route::get('list_ajax/{faculty_id}', 'NoteController@files_ajax');
    });

    Route::group(['prefix' => 'solutions','as'=>'solutions.'], function () {
        Route::get('/{faculty_id}', ['uses'=>'SolutionController@files','as'=>'index']);
        Route::post('/delete', ['uses'=>'SolutionController@delete','as'=>'delete']);
        Route::post('/upload', ['uses'=>'SolutionController@upload','as'=>'upload']);
    });

});

Route::group(['prefix' => 'profile','as'=>'profile.'], function () {
    Route::get('/{id}', ['uses'=>'UserController@view_profile','as'=>'view']);
});


Route::group(['prefix' => 'user','as'=>'user.'], function () {
    Route::get('/list', ['uses'=>'UserController@index','as'=>'index']);
    Route::post('/register', ['uses'=>'UserController@register','as'=>'register']);
    Route::get('/admin', ['uses'=>'UserController@admin_index','as'=>'index.admin']);
    Route::get('/permission', ['uses'=>'UserController@getPermission','as'=>'permission']);
    Route::Post('/permission/add', ['uses'=>'UserController@savePermission','as'=>'permission.add']);
    Route::get('/assign_permission/{id}', ['uses'=>'UserController@assign_permission', 'as'=>'assign_permission']);
    Route::post('/assign_permission/store', ['uses'=>'UserController@assign_permission_store', 'as'=>'assign_permission_store']);
    Route::post('/permission_view', ['uses'=>'UserController@permission_view', 'as'=>'permission_view']);
});

Route::group(['prefix' => 'job','as'=>'job.'], function () {
    Route::get('/', ['uses'=>'JobController@index','as'=>'index']);
    Route::post('/save', ['uses'=>'JobController@store','as'=>'save']);
    Route::get('/application/{job_id}', ['uses'=>'JobController@get_applications','as'=>'get_applications']);
    Route::post('/update', ['uses'=>'JobController@update','as'=>'update']);
});


Route::get('/setup', ["uses"=>'SetupController@setup'])->name('setup');
Route::post('/setup/run', ["uses"=>'SetupController@setup_run'])->name('setup.run');

resources/views/layouts/_partials/footer.blade.php
<footer class="footer text-center"> <?=date('Y') ?> &copy; HelpEr brought to you by <a href="#">Technician Group Of Nepal</a> </footer>

resources/views/layouts/_partials/header.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="">
    <title>Document - @yield('page_title')</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{ asset(STATIC_DIR.'assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    {{--<!-- This is Sidebar menu CSS -->--}}
    <link href="{{ asset(STATIC_DIR.'assets/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css') }}" rel="stylesheet">
    {{--<!-- This is a Animation CSS -->--}}
    <link href="{{ asset(STATIC_DIR.'assets/css/animate.css') }}" rel="stylesheet">
    {{--<!-- This is a Custom CSS -->--}}
    <link href="{{ asset(STATIC_DIR.'assets/css/style.css') }}" rel="stylesheet">
    {{--<!-- color CSS you can use different color css from css/colors folder -->--}}
    {{--<!-- We have chosen the skin-blue (default.css) for this starter--}}
         {{--page. However, you can choose any other skin from folder css / colors .--}}
         {{---->--}}
    <link href="{{ asset(STATIC_DIR.'assets/css/colors/megna-dark.css') }}" id="theme" rel="stylesheet">
    <link rel="icon" href="{{ asset(STATIC_DIR.'assets/icons/helper32.png') }}">
    {{--<script src="{{ asset(STATIC_DIR.'js/app.js') }}" defer></script>--}}
{{--    <link href="{{ asset(STATIC_DIR.'css/app.css') }}" rel="stylesheet">--}}
    <style>
        .sidebar {
            z-index: 900;
            position: absolute;
            width: 100%;
            top: 60px;
            height: auto;
            overflow: visible;
            transition: .05s ease-in;
        }
        .action-primary:hover{
            border: 1px solid blue;
        }
        .action-danger:hover{
            border: 1px solid red;
        }
        .action{
            display: none;
        }
        .title:hover .action {
            display: block;
            margin-left: -12px;
        }
        .vl {
            border-left: 1px solid green;
            margin-right: 4px;
            margin-left: 2px;
        }
    </style>
    @yield('css')
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

resources/views/layouts/_partials/main-navbar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav">
        <div class="sidebar-head">
            <h3>
                <span class="fa-fw open-close">
                    <i class="ti-menu hidden-xs"></i>
                    <i class="ti-close visible-xs"></i>
                </span>
                <span class="hide-menu">Navigation</span>
            </h3>
        </div>
        <ul class="nav" id="side-menu">
            <li>
                <a href="{{ route('home') }}" class="@if(Request::is('/')) active @endif"><i  class="mdi mdi-home fa-fw"></i> <span class="hide-menu">Dashboard</span></a>
            </li>
            @can('university-list')
                <li>
                    <a href="{{ route('university.index') }}" class="@if(Request::is('university')) active @endif"><i  class="mdi mdi-school fa-fw"></i> <span class="hide-menu">University</span></a>
                </li>
            @endcan
            <li>
                <a href="{{ route('files.index') }}" class="@if(Request::is('files') OR Request::is('files/*')) active @endif"><i  class="mdi mdi-file-document fa-fw"></i> <span class="hide-menu">Notes & Solutions</span></a>
            </li>
            @can('offer-list')
                <li>
                    <a href="{{ route('offers.index') }}" class="@if(Request::is('offers') OR Request::is('offers/*')) active @endif"><i  class="mdi mdi-cart-outline fa-fw"></i> <span class="hide-menu">Offers</span></a>
                </li>
            @endcan
            <li>
                <a href="{{ route('job.index') }}" class="@if(Request::is('job') OR Request::is('job/*')) active @endif"><i  class="mdi mdi-briefcase fa-fw"></i> <span class="hide-menu">Jobs/ Interns</span></a>
            </li>
            <li>
                <a href="javascript:void(0)" class="waves-effect @if(Request::is('user/*') OR Request::is('user')) active @endif">
                    <i class="mdi mdi-account-box-outline fa-fw"></i>
                    <span class="hide-menu">Users Management<span class="fa arrow"></span></span>
                </a>
                <ul class="nav nav-second-level">
                    <li><a href="{{ route('user.index.admin') }}"><i class="mdi mdi-account fa-fw"></i><span class="hide-menu">Admins</span></a></li>
                    <li><a href="{{ route('user.index') }}"><i class="mdi mdi-account fa-fw"></i><span class="hide-menu">Users</span></a></li>
                    <li><a href="{{ route('user.permission') }}"><i class="mdi mdi-lock fa-fw"></i><span class="hide-menu">Permission</span></a></li>
                </ul>
            </li>
            <li class="devider"></li>
        </ul>
    </div>
</div>

resources/views/layouts/_partials/scripts.blade.php
<!-- jQuery -->
<script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{{ asset(STATIC_DIR.'assets/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Sidebar menu plugin JavaScript -->
<script src="{{ asset(STATIC_DIR.'assets/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') }}"></script>
<!--Slimscroll JavaScript For custom scroll-->
<script src="{{ asset(STATIC_DIR.'assets/js/jquery.slimscroll.js') }}"></script>
<!--Wave Effects -->
<script src="{{ asset(STATIC_DIR.'assets/js/waves.js') }}"></script>
<!-- Custom Theme JavaScript -->
<script src="{{ asset(STATIC_DIR.'assets/js/custom.js') }}"></script>
@yield('script')

resources/views/layouts/_partials/top-navbar.blade.php
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <!-- Toggle icon for mobile view -->
        <div class="top-left-part">
            <!-- Logo -->
            <a class="logo" href="{{ route('home') }}">
            {{--<!-- Logo icon image, you can use font-icon also --><b>--}}
            {{--                    <!--This is dark logo icon--><img src="{{ asset(STATIC_DIR.'assets/icons/helper512.png') }}" width="25" alt="home" class="dark-logo" />--}}
            <!--This is light logo icon--><img src="{{ asset(STATIC_DIR.'assets/icons/helper512.png') }}" style="margin-bottom: 6px;padding-right: 10px;" width="45" alt="home" class="light-logo" />
            {{--</b>--}}
            <!-- Logo text image you can use text also -->
                <span class="hidden-xs">
                        {{--<!--This is dark logo text--><img src="{{ asset(STATIC_DIR.'assets/icons/helperwithpen.png') }}" alt="home" class="dark-logo" />--}}
                        <!--This is light logo text--><img src="{{ asset(STATIC_DIR.'assets/icons/helperwithoutpen.png') }}" alt="home" class="light-logo" width="80"/>
                     </span>
            </a>
        </div>
        <!-- /Logo -->

        <!-- This is the message dropdown -->
        <ul class="nav navbar-top-links navbar-right pull-right">
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="javascript:void(0)">
                    @if(!empty(Auth::user()->image))
                        <img src="{{ asset(STATIC_DIR.'storage/'.Auth::user()->image) }}" alt="user-img" width="36" class="img-circle">
                    @else
                        <img src="{{ asset(STATIC_DIR.'assets/icons/default-user.png') }}" alt="user-img" width="36" class="img-circle">
                    @endif
                    <b class="hidden-xs">{{ Auth::user()->name }}</b><span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    @if (Auth::check())
                        <li>
                            <div class="dw-user-box">
                                <div class="u-img">
                                    @if(!empty(Auth::user()->image))
                                        <img src="{{ asset(STATIC_DIR.'storage/'.Auth::user()->image) }}" alt="user-img" width="36" class="img-circle">
                                    @else
                                        <img src="{{ asset(STATIC_DIR.'assets/icons/default-user.png') }}" alt="user-img" width="36" class="img-circle">
                                    @endif
                                </div>
                                <div class="u-text">
                                    <h4>{{ Auth::user()->name }}</h4>
                                    <p class="text-muted">{{ Auth::user()->email ?? '' }}</p>
                                    <a href="{{route('profile')}}" class="btn btn-rounded btn-danger btn-sm">View Profile</a>
                                </div>
                            </div>
                        </li>
                    @endif
                    <li role="separator" class="divider"></li>
                    {{--<li><a href="javascript:void(0)"><i class="ti-user"></i> My Profile</a></li>--}}
                    {{--<li><a href="javascript:void(0)"><i class="ti-wallet"></i> My Balance</a></li>--}}
                    {{--<li><a href="javascript:void(0)"><i class="ti-email"></i> Inbox</a></li>--}}
                    {{--<li role="separator" class="divider"></li>--}}
                    {{--<li><a href="javascript:void(0)"><i class="ti-settings"></i> Account Setting</a></li>--}}
                    {{--<li role="separator" class="divider"></li>--}}
                    <li><a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-power-off text-danger"></i> Logout</a></li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </ul>
            </li>
        </ul>
    </div>
</nav>